# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='device',
        ),
        migrations.AddField(
            model_name='attribute',
            name='obs_type',
            field=models.CharField(default='NA', max_length=2),
            preserve_default=False,
        ),
    ]
