# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-25 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_auto_20171208_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='collected_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
