# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-05 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='location',
        ),
        migrations.AddField(
            model_name='device',
            name='location_address',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
